// types for Products
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const SINGLE_PRODUCT_LIST_REQUEST = "SINGLE_PRODUCT_LIST_REQUEST";
export const SINGLE_PRODUCT_LIST_SUCCESS = "SINGLE_PRODUCT_LIST_SUCCESS";
export const SINGLE_PRODUCT_LIST_FAIL = "SINGLE_PRODUCT_LIST_FAIL";
// types for Orders
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const SINGLE_ORDER_LIST_REQUEST = "SINGLE_ORDER_LIST_REQUEST";
export const SINGLE_ORDER_LIST_SUCCESS = "SINGLE_ORDER_LIST_SUCCESS";
export const SINGLE_ORDER_LIST_FAIL = "SINGLE_ORDER_LIST_FAIL";
// Add to Favorite
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
