// types for Products
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const CRAFT_PRODUCT_LIST_REQUEST = "CRAFT_PRODUCT_LIST_REQUEST";
export const CRAFT_PRODUCT_LIST_SUCCESS = "CRAFT_PRODUCT_LIST_SUCCESS";
export const CRAFT_PRODUCT_LIST_FAIL = "CRAFT_PRODUCT_LIST_FAIL";
export const CRAFT_SINGLE_PRODUCT_LIST_REQUEST =
  "CRAFT_SINGLE_PRODUCT_LIST_REQUEST";
export const CRAFT_SINGLE_PRODUCT_LIST_SUCCESS =
  "CRAFT_SINGLE_PRODUCT_LIST_SUCCESS";
export const CRAFT_SINGLE_PRODUCT_LIST_FAIL = "CRAFT_SINGLE_PRODUCT_LIST_FAIL";
export const SINGLE_PRODUCT_LIST_REQUEST = "SINGLE_PRODUCT_LIST_REQUEST";
export const SINGLE_PRODUCT_LIST_SUCCESS = "SINGLE_PRODUCT_LIST_SUCCESS";
export const SINGLE_PRODUCT_LIST_FAIL = "SINGLE_PRODUCT_LIST_FAIL";
export const ADD_PRODUCT_TO_WOOCOM_REQUEST = "ADD_PRODUCT_TO_WOOCOM_REQUEST";
export const ADD_PRODUCT_TO_WOOCOM_SUCCESS = "ADD_PRODUCT_TO_WOOCOM_SUCCESS";
export const ADD_PRODUCT_TO_WOOCOM_FAIL = "ADD_PRODUCT_TO_WOOCOM_FAIL";
// types for Orders
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const SINGLE_ORDER_LIST_REQUEST = "SINGLE_ORDER_LIST_REQUEST";
export const SINGLE_ORDER_LIST_SUCCESS = "SINGLE_ORDER_LIST_SUCCESS";
export const SINGLE_ORDER_LIST_FAIL = "SINGLE_ORDER_LIST_FAIL";
// Favorite
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
// Cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const EMPTY_CART = "EMPTY_CART";
// User
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
// Order
export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAIL = "ORDER_FAIL";
